version: "3"

services:
  scrapper:
    build: ./scrapper
    image: scrapper:stable
    entrypoint: /bin/bash
    command: -c "node /home/pptruser/scripts/scrapper.js"
    cap_add:
      - SYS_ADMIN
    ports:
      - "3000"
    volumes:
      - ./sharedFolder/:/home/pptruser/projects/
      - ./scrapper/scripts/scrapper.js:/home/pptruser/scripts/scrapper.js
  scrapper-api:
    build: ./scrapper-api
    image: scrapper-api:stable
    ports:
      - "8000:8000"
    volumes:
      - ./sharedFolder/:/root/projects/